LANG = {
    'EN':{
        'MON':'MON',
        'TUE':'TUE',
        'WED':'WED',
        'THU':'THU',
        'FRI':'FRI',
        'SAT':'SAT',
        'SUN':'SUN',
        'Monday':'Monday',
        'Tuesday':'Tuesday',
        'Wednesday':'Wednesday',
        'Thursday':'Thursday',
        'Friday':'Friday',
        'Saturday':'Saturday',
        'Sunday':'Sunday',
        'Edit':'Edit',
        'Stats':'Stats',
        'January':'January',
        'February':'February',
        'March':'March',
        'April':'April',
        'May':'May',
        'June':'June',
        'July':'July',
        'August':'August',
        'September':'September',
        'October':'October',
        'November':'November',
        'December':'December',
        'Time':'Time',
        'Delete':'Delete',
        'Close':'Close',
        'Home':'Home',
        'About':'About',
        'Account': 'Account',
        'Logout': 'Logout',
        'Users List':'Users List',
        'Add User':'Add User',
        'Go Back': 'Go Back',
        'Change Password': 'Change Password',
        'Reset Password': 'Reset Password',
        'Name':'Name',
        'Status':'Status',
        'Close date':'Close date',
        'Agent in charge':'Agent in charge',
        'Selling probability':'Selling probability',
        'Amount':'Amount',
        'Description':'Description',
        'Origin':'Origin',
        'Products':'Products',
        'Add Affair':'Add Affair',
        'Company':'Company',
        'Waiting':'Waiting',
        'In Progress':'In progress',
        'Done':'Done',
        'Pick a company':'Pick a company..',
        'Type':'Type',
        'Add':'Add',
        'Quantity':'Quantity',
        'Proba':'Proba',
        'Close dat':'Close dat',
        'Agent':'Agent',
        'Add a company':'Add a company',

    },
    'FR':{
        'MON':'LUN',
        'TUE':'MAR',
        'WED':'MER',
        'THU':'JEU',
        'FRI':'VEN',
        'SAT':'SAM',
        'SUN':'DIM',
        'Monday':'Lundi',
        'Tuesday':'Mardi',
        'Wednesday':'Mercredi',
        'Thursday':'Jeudi',
        'Friday':'Vendredi',
        'Saturday':'Samedi',
        'Sunday':'Dimanche',
        'Edit':'Modifier',
        'Stats':'Stats',
        'January':'Janvier',
        'February':'Février',
        'March':'Mars',
        'April':'Avril',
        'May':'Mai',
        'June':'Juin',
        'July':'Juillet',
        'August':'Août',
        'September':'Septembre',
        'October':'Octobre',
        'November':'Novembre',
        'December':'Décembre',
        'Reserved':'Reservé',
        'Time':'Horaire',
        'Delete':'Supprimer',
        'Close':'Fermer',
        'Home': 'Acceuil',
        'About':'A Propos',
        'Account': 'Profil',
        'Logout': 'Déconnexion',
        'Add User':'Utilisateur',
        'Go Back': 'Arrière',
        'Change Password': 'Modifier Mot De Passe',
        'Reset Password': 'Modifier Mot De Passe',
        'Name':'Nom',
        'Status':'Etat',
        'Close date':'Date clôture',
        'Agent in charge':'Résponsable',
        'Selling probability':'Probabilité de vente',
        'Amount':'Montant',
        'Description':'Description',
        'Origin':'Origine',
        'Products':'Produits',
        'Add Affair':'Ajouter Affaire',
        'Company':'Entreprise',
        'Waiting':'En attente',
        'In Progress':'En cours',
        'Done':'Terminé',
        'Pick a company':'Choisir entreprise..',
        'Type':'Type',
        'Add':'Ajouter',
        'Quantity':'Quantité',
        'Proba':'Proba',
        'Close dat':'Date clôt',
        'Agent':'Resp.',
        'Add a company':'Ajouter une entreprise',
        'Company information':'Informations entreprise',
        'Contact information':'Informations contact',
        "Confirm":"Confirmer",
        "Company name":"Nom entreprise",
        "Contact name":"Prénom contact",
        "Contact lastname":"Nom contact",
        "Contact email":"Email contact",
        "Contact phone number":"Téléphone contact",
        "Add family":"Ajouter catégorie de produit",
        "Parent family":"Catégorie parente"     ,
        "Add Product":"Ajouter Produit",
        "Selling price":"Prix de vente",
        "Estimated cost":"Coût estimé",
        'Tax category':"Catégorie de taxe",
        "Location":"Localité",
        "Family":"Catégorie de produit",
        "Barcode":"Code à barre",
        'Value (%)':'Valeur (%)',
        "Contact fullname":"Nom contact",
        "Contacts":"Contacts",
        "SKU":"Code",
        "Tax cat.":"Cat. taxe",
        "Category":"Catégory",
        "Price/Unit":"Prix unitaire",
        "In stock":"En stock",
        "Families":"Catégories produit",
        "Tax categories":"Catégories taxe",
        'Update':"Mettre à jour",
        "Sellers":"Fournisseurs",
        "Add Task":"Ajouter Tâche",
        "Edit Task":"Modifier taĉhe",
        "Priority":"Priorité",
        "Hour":"Heure",
        "Minute":"Minute",
        "Due date":"Date limite",
        "at":"à",
        "High":"Haute",
        "Medium":"Moyenne",
        "Low":"Basse",
        "Postpone":"Décaler",
        'Assigned to':"Assignée à",
        "Created by":"Créée par",
        "Previous tasks in chain":"En attente de",
        "By":"Par",
        "tasks where":"tâches où",
        "are late":"en retard",
        "affairs":"affaires",
        "My Tasks":"Mes Tâches",
        "My Affairs":"Mes affaires",
        "Purchase":"Achat",
        "Sale":"Vente",
        "Add Company":"Ajouter Entreprise",
        "Add Sale":"Ajouter Vente",
        "Add Purchase":"Ajouter Achat",
        "Users List":"Utilisateurs",
        "Tasks List":"Liste Tâches",
        "Products List":"Liste Produits",
        "Affairs List":"Liste Affaires",
        "Parameters":"Paramètres",
        "Cancel":"Annuler",
        "Add affairs":"Ajouter affaires",
        "Add company":"Ajouter entreprises",
        "Add products":"Ajouter produits",
        "Add tasks":"Ajouter tâches",
        "Add users":"Ajouter utilisateurs",
        "Check affairs list":"Voir liste des affaires",
        "Check companies list":"Voir liste des entreprises",
        "Check products list":"Voir liste des produits",
        "Check tasks list":"Voir liste des tâches",
        "Check users list":"Voir liste des utilisateurs",
        "Edit affairs":"Modifier affaire",
        "Edit company":"Modifier entreprise",
        "Edit products":"Modifier produit",
        "Edit tasks":"Modifier tâche",
        "Postpone tasks":"Décaler tâche",
        "Update affair status":"Modifier état affaire",
        "Update parameters":"Modifier paramètres ",
        "Update task status":"Modifier état tâche",
        "Roles":"Rôles",
        "Users":"Utilisateurs",
        "Inventory":"Inventaire",
        "Affairs":"Affaires",
        "Companies List":"Liste Entreprises",
        "User":"Utilisateur",
        "Product":"Produit",
        "Companies":"Entreprises",
        "Task":"Tâche",
        "Tasks":"Tâches",
        "Service":"Service",
        "Price":"Prix",
        "Welcome":"Bienvenue",
        "None":"Aucun",
        "Seller":"Fournisseur",
        "Invoice":"Facture",
        "Invoiced":"Facturée",
        "Non invoiced":"Non facturée",
        "Remarks":"Remarques",
        "Add Operation":"Ajouter Opération",
        "Created at":"Créée au",
        "Edit Affair":"Modifier Affaire",
        "Check daily report":"Voir le rapport journalier",
        "Daily Report":"Rapport Journalier",
        "Date":"Date",
        "Date created":"Date de création",
        "In":"Entrée",
        "Out":"Sortie",
        "Checkout":"Caisse",
        "Monthly Report":"Rapport Mensuel",
        "Monthly":"Mensuel",
        "Daily":"Journalier",
        "Reports":"Rapports",
        "Add presence":"Ajouter présence",
        "Day off":"Congé",
        "Presence":"Présence",
        "History":"Historique",
        "Unit":"Unité",
        'Progress':"Progrès",
        "Presence History":"Historique de présence",
        "Add new role":"Ajouter rôle",
        "Registration number":"Matricule fiscal",
        'Confirmed':"Confirmé",
        "Previsional":"Prévisionnel",
        "Plate":"Matricule"


    }
}